modules:
  better_spawn_protection: # works only for overworld
    enable: true
    size: 32
    offset:
      explode: 100
      break: 60
      place: 60
      fire: 0
      entity_spawn: 0
      damage: 0
      liquid: 60
      redstone: 60