proxycheck_apikey: ''
modules:
  better_spawn_protection: # works only for overworld
    enable: true
    size: 32
    offset:
      explode: 100
      break: 60
      place: 60
      fire: 0
      entity_spawn: 0
      damage: 0
      liquid: 60
      redstone: 60
  chat:
    enable: true
    format: # %1$s for username, %2$s for message
      admin: "&c%1$s&f: %2$s"
      mod: "&9%1$s&f: %2$s"
      vip: "&6&%1$s&f: %2$s"
      default: "%1$s: %2$s"
  webapi:
    enable: true
    port: 4200
  slots:
    enable: true
    add: 5
    limit: 100
    message: |
        Serwer jest pelny.
        VIP moze wchodzic na serwer nawet gdy jest pelny!
    