name: ${project.name}
main: pl.pivipi.core.Core
version: ${project.version}
api-version: 1.16
author: Minecon724
website: https://pivipi.pl
softdepend: [SimplixCore]
commands:
  zakup:
  stat:
  ip:
  core:
    aliases: pivipi
permissions:
  core.ip:
    default: op
  core.bypasssp:
    default: op
